### ISSUE TITLE
won't install

### ISSUE THREAD

**Issue by blogsdon** [dunleavy005/phylomoments#1]
library fails to install:

> library(devtools)
> install_github('dunleavy005/phylomoments')
Downloading GitHub repo dunleavy005/phylomoments@master
from URL https://api.github.com/repos/dunleavy005/phylomoments/zipball/master
Installing phylomoments
Installing 1 package: RcppArmadillo
trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/RcppArmadillo_0.7.100.3.0.tgz'
Content type 'application/x-gzip' length 1338030 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

The downloaded binary packages are in
	/var/folders/x1/ysh43wcj0_vfxv2vphlg3nd40000gq/T//RtmpMnvhtI/downloaded_packages
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/x1/ysh43wcj0_vfxv2vphlg3nd40000gq/T/RtmpMnvhtI/devtools86ac64ce7dc3/dunleavy005-phylomoments-2dfaf30'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library'  \
  --install-tests 

* installing *source* package ‘phylomoments’ ...
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/RcppArmadillo/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/RcppArmadillo/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c phylomoments.cpp -o phylomoments.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o phylomoments.so RcppExports.o phylomoments.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2 -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [phylomoments.so] Error 1
ERROR: compilation failed for package ‘phylomoments’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/phylomoments’

session info:

> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.11.1

loaded via a namespace (and not attached):
[1] httr_1.1.0    R6_2.1.2      tools_3.3.0   withr_1.0.1   curl_0.9.7   
[6] memoise_1.0.0 git2r_0.15.0  digest_0.6.9

**Comment by blogsdon** [comment]
This solves the issue on Mac OS X

curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2
sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C /

**Comment by dunleavy005** [comment]
Thanks for providing this informative error message. It seems that the issue is related to one of Mac OS X's R development tools being out of date (namely "gfortran").

The commands you provided above install the up-to-date "gfortran" libraries.
