### ISSUE TITLE
vignettes do not show up when listing with vignette function

### ISSUE THREAD

**Issue by blogsdon** [dunleavy005/phylomoments#2]
`> vignette(package='phylomoments')`
`no vignettes found`

**Comment by dunleavy005** [comment]
When you installed the package, did you run `install_github("dunleavy005/phylomoments", build_vignettes = TRUE)`?  The `install_github` function doesn't build the vignettes unless you specify the `build_vignettes` argument.

I will add this information to the README file. Thank you for bringing this to my attention.
